[package]
name = "allowed_combinations_of_let_and_set"
version = "0.1.0"
authors = ["main"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
